brace_style = "PreferSameLine"
chain_width = 80
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 110
struct_field_align_threshold = 100
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
